### ISSUE TITLE
Remove __pycache__ folder and add `*.pyc` to gitignore

### ISSUE THREAD

**Issue by Connor-Bowley** [MathieuLeclercq/SlicerJawSegmentation#12]
As the title says, remove all the __pycache__ folders which contain the compiled python code. Recommend adding a `.gitignore` file at the root of the repo with `*.pyc` in it.

**Comment by MathieuLeclercq** [comment]
Done. Thank you.

**Comment by Connor-Bowley** [comment]
On branch main the folder `SlicerJawSegmentation/CrownSegmentation/__pycache__` still exists.

**Comment by MathieuLeclercq** [comment]
Thanks, I missed that one. It should be good now.
